### ISSUE TITLE
error when applying FG NO Plage Tale Requiem

### ISSUE THREAD

**Issue by VelasquezZZ12** [artur-graniszewski/DLSS-Enabler#14]
I went to play A Plage Tale Requiem yesterday and I had problems with the frame generator when I left it on, it keeps the text out of sync like a hud error, but only in the text, dialogs and such.
I wanted to know if there is any fix for it?

**Comment by artur-graniszewski** [comment]
Hi, thanks for the feedback. This is a known issue, a bug in the game itself - instead of rendering the text as part of HUD layer, it prints it into the HUD-less resource.

This in turn means that general DLSS-to-FSR3 solution won't be able to mitigate the issue, but you can try DLSS Enabler 3.03.000.0 and enable Frame Generation provided by Optiscaler 0.7, as it provides the HUD detection mechanism (still Work in Progress, but might be able to detect the text).
