### ISSUE TITLE
Warhammer 40K Space Marine 2 support request

### ISSUE THREAD

**Issue by denver8989** [artur-graniszewski/DLSS-Enabler#9]
i'm so devastated space marine 2 does not support fsr 3.1 out of the box as a handheld gamer it's pretty sad i get pretty lousy perfomance on the legion go without fsr 3 and or mods like this one, i don't know if its right to put this in as an issue however even if this does not happen i have a huge appreciation for this mod love your work !

**Comment by VelasquezZZ12** [comment]
If you use the dlss enabler you will have support for the fsr 3.1 upscaler and also xess but to use xess you need to turn off rcas because it closes the game
but regarding FG the game does not have native support for any option from amd and nvidia so with this mod as far as I know there is no way to connect it.
You can try with lukefz mods and the FG will work but you will have problems with the hud

**Comment by artur-graniszewski** [comment]
Yes, that is true, only upscaler is available in that game.

DLSS Enabler does not add Frame Generation to games that do not support DLSSG already. While it is technically doable, no such implementation is planned for now, as it would come with rhe drawback that @VelasquezZZ12 already mentioned: HUD flickering

**Comment by denver8989** [comment]
yeah got you yeah luke fz mod works but the ui is ghosting crazy will wait for official support.
